### ISSUE TITLE
Describe channels

### ISSUE THREAD

**Issue by emcwhirter-usgs** [usgs/geomag-plots#39] opened 2015-08-05 19:20 UTC
We need a way to describe the channels to users. How we do this is up to us: hover text, inline summaries, links to pages with more information, etc.

**Comment by cafinn-usgs** [comment] 2015-12-09 22:17
Previously suggested:
1) The title should be changed from "Geomag Plots" something like "Earth's Magnetic Field Plots".  This would make a little more sense to a public user of this web page.  It would be nice if the title could be centered.

2) The subtitle "H Channel" should be changed to "Horizontal (H) Component" and similarly for the other components.  This is a more correct terminology and is less cryptic to the public.

**Comment by cafinn-usgs** [comment] 2015-12-09 22:49
We could also point them to our Instrumentation page, which describes H, D, Z, and F in greater detail.

http://geomag.usgs.gov/monitoring/instrumentation.php

or to the "Introduction to Geomag" page, which describes X, Y, Z.

http://geomag.usgs.gov/learn/introtogeomag.php

**Comment by hasimpson-usgs** [comment] 2016-05-31 21:34
Duplicate of #68.

**Closed** 2016-05-31 21:34 UTC
Labels: enhancement
